-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-02-07 16:53:43 GMT
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c

ALTER TABLE `booked_places` DROP FOREIGN KEY `booked_places_bookings_FK`;
ALTER TABLE `booked_places` DROP FOREIGN KEY `booked_places_time_slots_FK`;
ALTER TABLE `booked_places` DROP FOREIGN KEY `booked_places_tracks_FK`;

ALTER TABLE `bookings` DROP FOREIGN KEY `bookings_customers_FK`;

ALTER TABLE `track_blocks` DROP FOREIGN KEY `track_blocks_time_slots_FK`;
ALTER TABLE `track_blocks` DROP FOREIGN KEY `track_blocks_tracks_FK`;
ALTER TABLE `track_schedules` DROP FOREIGN KEY `track_schedules_time_slots_FK`;
ALTER TABLE `track_schedules` DROP FOREIGN KEY `track_schedules_tracks_FK`;

ALTER TABLE `booked_places` DROP INDEX `idx_booked_places_availability`;
ALTER TABLE `bookings` DROP INDEX `idx_bookings_status_reserved`;

ALTER TABLE `track_blocks` DROP INDEX `track_blocks_UN`;
ALTER TABLE `track_schedules` DROP INDEX `track_schedules_UN`;
ALTER TABLE `time_slots` DROP INDEX `time_slots_UN`;
ALTER TABLE `tracks` DROP INDEX `tracks_UN`;
ALTER TABLE `customers` DROP INDEX `customer_email_UN`;

DROP VIEW IF EXISTS v_track_availability_view;
DROP TABLE IF EXISTS booked_places;
DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS time_slots;
DROP TABLE IF EXISTS track_blocks;
DROP TABLE IF EXISTS track_schedules;
DROP TABLE IF EXISTS tracks;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY
-- predefined type, no DDL - XMLTYPE

CREATE TABLE booked_places 
    ( 
        id INT NOT NULL, 
        bookings_id INT NOT NULL, 
        tracks_id INT NOT NULL, 
        time_slots_id INT NOT NULL, 
        booking_date DATETIME NOT NULL, 
        quantity INT NOT NULL 
    ) 
;

CREATE TABLE bookings 
    ( 
        id INT NOT NULL, 
        status VARCHAR (20) NOT NULL, 
        created_at DATETIME NOT NULL,
        updated_at DATETIME,
        reserved_until DATETIME, 
        customers_id INT NOT NULL 
    ) 
;


CREATE TABLE customers 
    ( 
        id INT NOT NULL, 
        first_name VARCHAR (50) NOT NULL, 
        last_name VARCHAR (50) NOT NULL, 
        email VARCHAR (50) NOT NULL, 
        updated_at DATETIME, 
        created_at DATETIME NOT NULL 
    ) 
;

CREATE TABLE time_slots 
    ( 
        id INT NOT NULL, 
        start_time VARCHAR (5) NOT NULL, 
        end_time VARCHAR (5) NOT NULL, 
        duration_in_minutes INT NOT NULL 
    ) 
;

CREATE TABLE track_blocks 
    ( 
        id INT NOT NULL, 
        block_date DATETIME NOT NULL, 
        reason VARCHAR (150) NOT NULL, 
        created_at DATETIME NOT NULL, 
        tracks_id INT NOT NULL, 
        time_slots_id INT NOT NULL 
    ) 
;

CREATE TABLE track_schedules 
    ( 
        id INT NOT NULL, 
        day_of_week SMALLINT NOT NULL, 
        is_open TINYINT(1) NOT NULL, 
        time_slots_id INT NOT NULL, 
        tracks_id INT NOT NULL 
    ) 
;

CREATE TABLE tracks 
    ( 
        id INT NOT NULL, 
        name VARCHAR (50) NOT NULL, 
        max_karts INT NOT NULL, 
        is_active TINYINT(1) NOT NULL, 
        updated_at DATETIME, 
        created_at DATETIME NOT NULL 
    ) 
;

-- Primary Keys with auto increment, to enable the utilisation of INSERT operations without handling ID, since no usage of UUIDs as no application layer
ALTER TABLE booked_places MODIFY id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE bookings MODIFY id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE customers MODIFY id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE time_slots MODIFY id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE track_blocks MODIFY id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE track_schedules MODIFY id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE tracks MODIFY id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;

-- Indexes
CREATE INDEX idx_booked_places_availability ON booked_places 
    ( 
        tracks_id ASC, 
        time_slots_id ASC, 
        booking_date ASC 
    ) 
;

CREATE INDEX idx_bookings_status_reserved ON bookings 
    ( 
        status ASC, 
        reserved_until ASC 
    ) 
;

-- Checks
ALTER TABLE bookings 
    ADD CONSTRAINT booking_status_CK 
    CHECK (UPPER(status) IN ('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED'));

ALTER TABLE booked_places 
    ADD CONSTRAINT booked_places_quantity_CK
    CHECK (quantity > 0);

ALTER TABLE time_slots 
    ADD CONSTRAINT time_slots_dur_CK
    CHECK (duration_in_minutes = 90);

ALTER TABLE time_slots 
    ADD CONSTRAINT time_slots_time_format_CK 
    CHECK (REGEXP_LIKE(start_time, '^([0-1][0-9]|2[0-3]):[0-5][0-9]$') AND REGEXP_LIKE(end_time, '^([0-1][0-9]|2[0-3]):[0-5][0-9]$'));

ALTER TABLE track_schedules 
    ADD CONSTRAINT track_schedules_day_CK
    CHECK (day_of_week BETWEEN 1 AND 7);

ALTER TABLE track_schedules 
    ADD CONSTRAINT track_schedules_open_CK
    CHECK (is_open IN (0, 1));

ALTER TABLE tracks 
    ADD CONSTRAINT tracks_max_karts_CK
    CHECK (max_karts > 0);

ALTER TABLE tracks 
    ADD CONSTRAINT tracks_open_CK
    CHECK (is_active IN (0, 1));

-- Unique Constraints
ALTER TABLE customers 
    ADD CONSTRAINT customer_email_UN UNIQUE ( email );

ALTER TABLE time_slots
    ADD CONSTRAINT time_slots_UN UNIQUE ( start_time, end_time, duration_in_minutes );

ALTER TABLE track_blocks 
    ADD CONSTRAINT track_blocks_UN UNIQUE ( tracks_id, time_slots_id, block_date );

ALTER TABLE track_schedules 
    ADD CONSTRAINT track_schedules_UN UNIQUE ( tracks_id, day_of_week, time_slots_id );

ALTER TABLE tracks 
    ADD CONSTRAINT tracks_UN UNIQUE ( name ) ;

-- Foreign Keys
ALTER TABLE booked_places 
    ADD CONSTRAINT booked_places_bookings_FK FOREIGN KEY (bookings_id) REFERENCES bookings (id) 
    ON DELETE CASCADE;

ALTER TABLE booked_places 
    ADD CONSTRAINT booked_places_time_slots_FK FOREIGN KEY (time_slots_id) REFERENCES time_slots (id);

ALTER TABLE booked_places 
    ADD CONSTRAINT booked_places_tracks_FK FOREIGN KEY (tracks_id) REFERENCES tracks (id);

ALTER TABLE bookings 
    ADD CONSTRAINT bookings_customers_FK FOREIGN KEY (customers_id) REFERENCES customers (id) 
    ON DELETE CASCADE;

ALTER TABLE track_blocks 
    ADD CONSTRAINT track_blocks_time_slots_FK FOREIGN KEY (time_slots_id) REFERENCES time_slots (id);

ALTER TABLE track_blocks 
    ADD CONSTRAINT track_blocks_tracks_FK FOREIGN KEY (tracks_id) REFERENCES tracks (id) 
    ON DELETE CASCADE;

ALTER TABLE track_schedules 
    ADD CONSTRAINT track_schedules_time_slots_FK FOREIGN KEY (time_slots_id) REFERENCES time_slots (id);

ALTER TABLE track_schedules 
    ADD CONSTRAINT track_schedules_tracks_FK FOREIGN KEY (tracks_id) REFERENCES tracks (id) 
    ON DELETE CASCADE;