-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-02-07 16:53:43 GMT
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c

DROP VIEW v_track_availability_view CASCADE CONSTRAINTS;
DROP TABLE booked_places CASCADE CONSTRAINTS;
DROP TABLE bookings CASCADE CONSTRAINTS;
DROP TABLE customers CASCADE CONSTRAINTS;
DROP TABLE time_slots CASCADE CONSTRAINTS;
DROP TABLE track_blocks CASCADE CONSTRAINTS;
DROP TABLE track_schedules CASCADE CONSTRAINTS;
DROP TABLE tracks CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY
-- predefined type, no DDL - XMLTYPE

CREATE TABLE booked_places 
    ( 
        id INTEGER NOT NULL, 
        bookings_id INTEGER NOT NULL, 
        tracks_id INTEGER NOT NULL, 
        time_slots_id INTEGER NOT NULL, 
        booking_date DATE NOT NULL, 
        quantity INTEGER NOT NULL 
    ) 
;

ALTER TABLE booked_places 
    ADD 
    CHECK (quantity > 0);

CREATE INDEX idx_booked_places_availability ON booked_places 
    ( 
        tracks_id ASC, 
        time_slots_id ASC, 
        booking_date ASC 
    ) 
;

ALTER TABLE booked_places 
    ADD CONSTRAINT booked_places_PK PRIMARY KEY ( id );

CREATE TABLE bookings 
    ( 
        id INTEGER NOT NULL, 
        status VARCHAR (20) NOT NULL, 
        created_at DATE NOT NULL, 
        reserved_until DATE, 
        customers_id INTEGER NOT NULL 
    ) 
;
CREATE INDEX idx_bookings_status_reserved ON bookings 
    ( 
        status ASC, 
        reserved_until ASC 
    ) 
;

ALTER TABLE bookings 
    ADD CONSTRAINT booking_status_CK 
    CHECK (UPPER(status) IN ('PENDING', 'RESERVED', 'CONFIRMED', 'CANCELLED', 'COMPLETED'));

ALTER TABLE bookings 
    ADD CONSTRAINT bookings_PK PRIMARY KEY ( id );

CREATE TABLE customers 
    ( 
        id INTEGER NOT NULL, 
        first_name VARCHAR (50) NOT NULL, 
        last_name VARCHAR (50) NOT NULL, 
        email VARCHAR (50) NOT NULL, 
        updated_at DATE NOT NULL, 
        created_at DATE NOT NULL 
    ) 
;

ALTER TABLE customers 
    ADD CONSTRAINT customers_PK PRIMARY KEY ( id );

ALTER TABLE customers 
    ADD CONSTRAINT INDEX_1 UNIQUE ( email );

CREATE TABLE time_slots 
    ( 
        id INTEGER NOT NULL, 
        start_time VARCHAR (5) NOT NULL, 
        end_time VARCHAR (5) NOT NULL, 
        duration_in_minutes INTEGER NOT NULL 
    ) 
;

ALTER TABLE time_slots 
    ADD 
    CHECK (duration_in_minutes = 90);

ALTER TABLE time_slots 
    ADD CONSTRAINT chk_time_format 
    CHECK (REGEXP_LIKE(start_time, '^([0-1][0-9]|2[0-3]):[0-5][0-9]$') AND REGEXP_LIKE(end_time, '^([0-1][0-9]|2[0-3]):[0-5][0-9]$'));

ALTER TABLE time_slots 
    ADD CONSTRAINT time_slots_PK PRIMARY KEY ( id );

CREATE TABLE track_blocks 
    ( 
        id INTEGER NOT NULL, 
        block_date DATE NOT NULL, 
        reason VARCHAR (150) NOT NULL, 
        created_at DATE NOT NULL, 
        tracks_id INTEGER NOT NULL, 
        time_slots_id INTEGER NOT NULL 
    ) 
;

ALTER TABLE track_blocks 
    ADD CONSTRAINT track_blocks_PK PRIMARY KEY ( id );

ALTER TABLE track_blocks 
    ADD CONSTRAINT track_blocks_UN UNIQUE ( tracks_id, time_slots_id, block_date );

CREATE TABLE track_schedules 
    ( 
        id INTEGER NOT NULL, 
        day_of_week SMALLINT NOT NULL, 
        is_open TINYINT(1) NOT NULL, 
        time_slots_id INTEGER NOT NULL, 
        tracks_id INTEGER NOT NULL 
    ) 
;

ALTER TABLE track_schedules 
    ADD 
    CHECK (day_of_week BETWEEN 1 AND 7);

ALTER TABLE track_schedules 
    ADD 
    CHECK (is_open IN (0, 1));

ALTER TABLE track_schedules 
    ADD CONSTRAINT track_schedules_PK PRIMARY KEY ( id );

ALTER TABLE track_schedules 
    ADD CONSTRAINT track_schedules_UN UNIQUE ( tracks_id, day_of_week, time_slots_id );

CREATE TABLE tracks 
    ( 
        id INTEGER NOT NULL, 
        name VARCHAR (50) NOT NULL, 
        max_karts INTEGER NOT NULL, 
        is_active TINYINT(1) NOT NULL, 
        updated_at DATE NOT NULL, 
        created_at DATE NOT NULL 
    ) 
;

ALTER TABLE tracks 
    ADD 
    CHECK (max_karts > 0);

ALTER TABLE tracks 
    ADD 
    CHECK (is_active IN (0, 1));

ALTER TABLE tracks 
    ADD CONSTRAINT tracks_PK PRIMARY KEY ( id );

ALTER TABLE booked_places 
    ADD CONSTRAINT booked_places_bookings_FK FOREIGN KEY (bookings_id) REFERENCES bookings (id) 
    ON DELETE CASCADE
    NOT DEFERRABLE;

ALTER TABLE booked_places 
    ADD CONSTRAINT booked_places_time_slots_FK FOREIGN KEY (time_slots_id) REFERENCES time_slots (id) 
    NOT DEFERRABLE;

ALTER TABLE booked_places 
    ADD CONSTRAINT booked_places_tracks_FK FOREIGN KEY (tracks_id) REFERENCES tracks (id) 
    NOT DEFERRABLE;

ALTER TABLE bookings 
    ADD CONSTRAINT bookings_customers_FK FOREIGN KEY (customers_id) REFERENCES customers (id) 
    ON DELETE CASCADE 
    NOT DEFERRABLE;

ALTER TABLE track_blocks 
    ADD CONSTRAINT track_blocks_time_slots_FK FOREIGN KEY (time_slots_id) REFERENCES time_slots (id) 
    NOT DEFERRABLE;

ALTER TABLE track_blocks 
    ADD CONSTRAINT track_blocks_tracks_FK FOREIGN KEY (tracks_id) REFERENCES tracks (id) 
    ON DELETE CASCADE
    NOT DEFERRABLE;

ALTER TABLE track_schedules 
    ADD CONSTRAINT track_schedules_time_slots_FK FOREIGN KEY (time_slots_id) REFERENCES time_slots (id) 
    NOT DEFERRABLE;

ALTER TABLE track_schedules 
    ADD CONSTRAINT track_schedules_tracks_FK FOREIGN KEY (tracks_id) REFERENCES tracks (id) 
    ON DELETE CASCADE
    NOT DEFERRABLE;