-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-01-23 11:51:41 GMT
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE booking_items 
    ( 
        id INTEGER  NOT NULL,
        bookings_id INTEGER NOT NULL,
        tracks_id INTEGER NOT NULL,
        time_slots_id INTEGER NOT NULL,
        booking_date DATE NOT NULL 
    ) 
;

ALTER TABLE booking_items 
    ADD CONSTRAINT booking_items_PK PRIMARY KEY ( id ) ;

ALTER TABLE booking_items 
    ADD CONSTRAINT booking_items__UN UNIQUE ( tracks_id,time_slots_id,booking_date ) ;

CREATE TABLE bookings 
    ( 
        id INTEGER NOT NULL,
        status VARCHAR2 (20 CHAR) NOT NULL,
        created_at DATE NOT NULL,
        customers_id INTEGER NOT NULL 
    ) 
;

ALTER TABLE bookings 
    ADD CONSTRAINT booking_status_CK CHECK (UPPER(status) IN ('PENDING','CONFIRMED','CANCELLED','COMPLETED'))
;
ALTER TABLE bookings 
    ADD CONSTRAINT bookings_PK PRIMARY KEY ( id ) ;

CREATE TABLE customers 
    ( 
        id INTEGER NOT NULL,
        first_name VARCHAR2 (50 CHAR) NOT NULL,
        last_name VARCHAR2 (50 CHAR) NOT NULL,
        email VARCHAR2 (50 CHAR) NOT NULL,
        updated_at DATE NOT NULL,
        created_at DATE NOT NULL 
    ) 
;

ALTER TABLE customers 
    ADD CONSTRAINT customers_PK PRIMARY KEY ( id ) ;

CREATE TABLE time_slots 
    ( 
        id INTEGER NOT NULL,
        start_time DATE NOT NULL,
        end_time DATE NOT NULL,
        duration_in_minutes INTEGER  OT NULL 
    ) 
;

ALTER TABLE time_slots 
    ADD CONSTRAINT time_slots_PK PRIMARY KEY ( id ) ;

CREATE TABLE track_blocks 
    ( 
        id INTEGER NOT NULL,
        block_date DATE NOT NULL,
        reason VARCHAR2 (150 CHAR) NOT NULL,
        created_at DATE NOT NULL,
        tracks_id INTEGER NOT NULL,
        time_slots_id INTEGER NOT NULL 
    ) 
;

ALTER TABLE track_blocks 
    ADD CONSTRAINT track_blocks_PK PRIMARY KEY ( id ) ;

ALTER TABLE track_blocks 
    ADD CONSTRAINT track_blocks__UN UNIQUE ( tracks_id,time_slots_id,block_date ) ;

CREATE TABLE track_schedules 
    ( 
        id INTEGER NOT NULL,
        day_of_week SMALLINT NOT NULL,
        is_open NUMBER NOT NULL,
        time_slots_id INTEGER NOT NULL,
        tracks_id INTEGER NOT NULL 
    ) 
;

ALTER TABLE track_schedules 
    ADD CONSTRAINT track_schedules_PK PRIMARY KEY ( id ) ;

ALTER TABLE track_schedules 
    ADD CONSTRAINT track_schedules__UN UNIQUE ( tracks_id,day_of_week,time_slots_id ) ;

CREATE TABLE tracks 
    ( 
        id INTEGER NOT NULL,
        name VARCHAR2 (50 CHAR) NOT NULL,
        is_active NUMBER NOT NULL,
        updated_at DATE NOT NULL,
        created_at DATE NOT NULL 
    ) 
;

ALTER TABLE tracks 
    ADD CONSTRAINT tracks_PK PRIMARY KEY ( id ) ;

ALTER TABLE booking_items 
    ADD CONSTRAINT booking_items_bookings_FK FOREIGN KEY ( bookings_id) REFERENCES bookings (id) ON DELETE CASCADE 
;

ALTER TABLE booking_items 
    ADD CONSTRAINT booking_items_time_slots_FK FOREIGN KEY ( time_slots_id ) REFERENCES time_slots ( id ) 
;

ALTER TABLE booking_items 
    ADD CONSTRAINT booking_items_tracks_FK FOREIGN KEY ( tracks_id ) REFERENCES tracks ( id ) 
;

ALTER TABLE bookings 
    ADD CONSTRAINT bookings_customers_FK FOREIGN KEY ( customers_id ) REFERENCES customers ( id ) ON DELETE CASCADE 
;

ALTER TABLE track_blocks 
    ADD CONSTRAINT track_blocks_time_slots_FK FOREIGN KEY ( time_slots_id ) REFERENCES time_slots ( id ) 
;

ALTER TABLE track_blocks 
    ADD CONSTRAINT track_blocks_tracks_FK FOREIGN KEY ( tracks_id ) REFERENCES tracks ( id ) 
;

ALTER TABLE track_schedules 
    ADD CONSTRAINT track_schedules_time_slots_FK FOREIGN KEY ( time_slots_id ) REFERENCES time_slots ( id ) ON DELETE CASCADE 
;

ALTER TABLE track_schedules 
    ADD CONSTRAINT track_schedules_tracks_FK FOREIGN KEY ( tracks_id ) REFERENCES tracks ( id ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             0
-- ALTER TABLE                             19
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
